nodes:
- address: 172.16.10.110
  port: "22"
  internal_address: 172.16.10.110
  role:
  - controlplane
  - worker
  - etcd
  hostname_override: ""
  user: david
  docker_socket: ""
  ssh_key: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn
    NhAAAAAwEAAQAAAQEAtgUOaulgJxARN+SGzxISifJuengH5Fzis6IRyaYr+wYdZ3RXO7ES
    gSsFNwMHuxIGj+A6RexkeP9slxAOx+0OMWB6m0C4Pd5esiK/Hi1h7/uG4gUfbl4j8C9Vsk
    +ofIkY2qeChz6ZuhVdOIpJZKrkYF8MhCmoKlt8Spc8dv+z45wvSe7rPmVcnHPtyv59Ywcn
    NwI7UWWF45agGQw2Ru4pdn+hGp+PKxZKKsiK79ZLU0OzXr0wqa7Df6iGiOPrt6xnI8UVgC
    V92F9iOKAG4kkpgjhR/kqnecDn8OjfPW+Hs+OtgcjVENlm5hvEEvJqI7zVx0gCOQXnJGEW
    ZZW4AEgvxwAAA9gKsiXPCrIlzwAAAAdzc2gtcnNhAAABAQC2BQ5q6WAnEBE35IbPEhKJ8m
    56eAfkXOKzohHJpiv7Bh1ndFc7sRKBKwU3Awe7EgaP4DpF7GR4/2yXEA7H7Q4xYHqbQLg9
    3l6yIr8eLWHv+4biBR9uXiPwL1WyT6h8iRjap4KHPpm6FV04iklkquRgXwyEKagqW3xKlz
    x2/7PjnC9J7us+ZVycc+3K/n1jByc3AjtRZYXjlqAZDDZG7il2f6Ean48rFkoqyIrv1ktT
    Q7NevTCprsN/qIaI4+u3rGcjxRWAJX3YX2I4oAbiSSmCOFH+Sqd5wOfw6N89b4ez462ByN
    UQ2WbmG8QS8mojvNXHSAI5BeckYRZllbgASC/HAAAAAwEAAQAAAQEAr/13kTuQsnRAkbAu
    ACzTK/nxhAxmZRDCSTkcxcIbqByjdZHxfk+ZOrbj1eriIKgvHBGLhmwoQS2GSxFFmVzFak
    yEf3Q2L+u/17Ds5TqwBR9HrWWSnF39lY/O5hdLKw5Lr65i8G1AqcFaXv6mM+Vf5yY/rdGx
    PTMzm9NarRxTTG/nWi+qZOMs13HE4zA0mUX8EnEIdBX+09Hz7Ge1rFhTlPFSe+3BgA1M2M
    k7AuNL/jVe6Hcg5DZ182wgC9KIVJ4C9eHoOp+sluUJs6Awh2iKxRXsK2FDl6Vvzu6jzBRJ
    fA7xqf+e5lYV37fKYZSBs9nNouxMYEJIq5RrG4mLn6fPgQAAAIEAwBL7KlRlibpVSOnTV0
    T9/1T4XOSykHszixoRoMnWZQvnJRTsfgayINVnKkU0TkolW/DZUpC7bbjI6qN9Y0RgRlVd
    fzlISq6Rt2YVsdnikYiWIoD3RLZ+hGlx/3XkhGpHvNqWGhVI6BdjE0JdnvbSuABiBkq1hR
    6C9UzLtTGmSBsAAACBAN3iZKqNFinJyXpeKdm9yEUsT6ux1sBr2hZfCX8w5fpDiL4zcamO
    P8Q6XeAY6GhHfBM4+zxm1Oc7gGtjvjDKAGx7/8xwJGnPRxIdThQ+w7wMn9xa5WvNU0OVpp
    +aXcDb72S8qs1VK13xwODGIV9cN7X4ZRRsn9rMZa5hIJfvOA+nAAAAgQDSAYy06elsZAX4
    4Rspp7UrW75zhDBUABu40M5OxcG6CIhOINRU+wxM4rZtOH6Yzv8Goqq38j9DqLAxOFGpJ9
    73RS66wTEeBzrgfpFVymPUfU8m/WzyE6vBaSu5/42jMWosVzDzNcHYrVMhcjtOPwzSk3+W
    bTqtyqQ8bP6WGmfi4QAAABtkYXZpZEB2aXJ0dWFsdGhvdWdodHMuY28udWsBAgMEBQY=
    -----END OPENSSH PRIVATE KEY-----
  ssh_key_path: ""
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    uid: 0
    gid: 0
    snapshot: null
    retention: ""
    creation: ""
    backup_config: null
  kube-api:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    service_cluster_ip_range: ""
    service_node_port_range: ""
    pod_security_policy: false
    always_pull_images: false
    secrets_encryption_config: null
    audit_log: null
    admission_configuration: null
    event_rate_limit: null
  kube-controller:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    cluster_cidr: ""
    service_cluster_ip_range: ""
  scheduler:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
  kubelet:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    cluster_domain: ""
    infra_container_image: ""
    cluster_dns_server: ""
    fail_swap_on: false
    generate_serving_certificate: false
  kubeproxy:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
network:
  plugin: ""
  options: {}
  mtu: 0
  node_selector: {}
  update_strategy: null
authentication:
  strategy: ""
  sans: []
  webhook: null
addons: ""
addons_include: []
system_images:
  etcd: ""
  alpine: ""
  nginx_proxy: ""
  cert_downloader: ""
  kubernetes_services_sidecar: ""
  kubedns: ""
  dnsmasq: ""
  kubedns_sidecar: ""
  kubedns_autoscaler: ""
  coredns: ""
  coredns_autoscaler: ""
  nodelocal: ""
  kubernetes: ""
  flannel: ""
  flannel_cni: ""
  calico_node: ""
  calico_cni: ""
  calico_controllers: ""
  calico_ctl: ""
  calico_flexvol: ""
  canal_node: ""
  canal_cni: ""
  canal_flannel: ""
  canal_flexvol: ""
  weave_node: ""
  weave_cni: ""
  pod_infra_container: ""
  ingress: ""
  ingress_backend: ""
  metrics_server: ""
  windows_pod_infra_container: ""
ssh_key_path: ""
ssh_cert_path: ""
ssh_agent_auth: false
authorization:
  mode: ""
  options: {}
ignore_docker_version: false
kubernetes_version: v1.18.3-rancher2-2
private_registries: []
ingress:
  provider: ""
  options: {}
  node_selector: {}
  extra_args: {}
  dns_policy: ""
  extra_envs: []
  extra_volumes: []
  extra_volume_mounts: []
  update_strategy: null
cluster_name: ""
cloud_provider:
  name: ""
prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""
  ssh_cert: ""
  ssh_cert_path: ""
monitoring:
  provider: ""
  options: {}
  node_selector: {}
  update_strategy: null
  replicas: null
restore:
  restore: false
  snapshot_name: ""
dns: null
upgrade_strategy:
  max_unavailable_worker: ""
  max_unavailable_controlplane: ""
  drain: false
  node_drain_input: null
